# Generated by Django 4.0.2 on 2022-02-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_tweetphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetphoto',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
