# Generated by Django 4.0.2 on 2022-02-28 19:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0003_alter_tweetphoto_deleted_at'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='tweetphoto',
            index_together={('has_deleted', 'created_at'), ('tweet', 'order'), ('user', 'created_at'), ('status', 'created_at')},
        ),
    ]
